---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronjobber
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cronjobber
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: cronjobber
    spec:
      serviceAccountName: cronjobber
      securityContext:
        fsGroup: 2 #daemon
      containers:
      - name: cronjobber
        image: quay.io/hiddeco/cronjobber:0.3.0
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        args:
        - --log-level=info
